"""add role column to users

Revision ID: b092eaa491d6
Revises: bccece371b6f
Create Date: 2026-06-12 15:19:18.773836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b092eaa491d6'
down_revision: Union[str, None] = 'bccece371b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('user_role', sa.String(), nullable=False, server_default='CUSTOMER'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
